name: Relase PWSH Module as draft

on:
  push:
    branches:
      - main
    paths:
      - 'Modules/**' #Only when changues on main modules folder

jobs:
  buildAndRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout 
      uses: actions/checkout@v4

    - name: Release tag
      id: generateTag
      run: |
        dateTime=$(date +'%Y.%m.%d')
        echo "releaseTag=v${dateTime}.${{ github.run_number }}" >> $GITHUB_OUTPUT

    - name: Zip modules folder
      run: |
        cd Modules
        zip -r ../modules-artifact.zip ./*
        cd ..

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.generateTag.outputs.releaseTag }}
        name: Release ${{ steps.generateTag.outputs.releaseTag }}
        draft: true
        prerelease: false
        files: modules-artifact.zip