name: Relase PWSH Module as draft

on:
  push:
    tags:
      - "v*.*.*"

  workflow_dispatch:

jobs:
  buildAndRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
    - name: Checkout 
      uses: actions/checkout@v5


    - name: Zip modules folder
      run: |
        cd Modules
        zip -r ../modules-artifact.zip ./*
        cd ..

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{github.ref_name}}
        name: Release ${{github.ref_name}}
        draft: true
        prerelease: false
        files: modules-artifact.zip